// Post-processes the openapi-zod-client output for this project:
//  1. Rewrites Zod v3 string-format helpers to their Zod v4 equivalents, because
//     the project pins Zod v4 and eslint `strictTypeChecked` forbids the deprecated forms.
//  2. Prepends a generated-file banner.
// Invoked by the `generate:api` npm script after generation; see package.json.
import { readFileSync, writeFileSync } from 'node:fs';

const OUT = 'src/shared/api/schemas.gen.ts';

const banner = [
  '// @generated by `bun run generate:api` from openapi/voidforge.json — DO NOT EDIT.',
  '// To refresh: start the API, save GET /swagger/v1/swagger.json to',
  '// openapi/voidforge.json, then run `bun run generate:api`.',
  '',
  '',
].join('\n');

let src = readFileSync(OUT, 'utf8');
src = src
  .replaceAll('z.string().uuid()', 'z.uuid()')
  .replaceAll('z.string().datetime(', 'z.iso.datetime(');

writeFileSync(OUT, banner + src);
