// @generated by `bun run generate:api` from openapi/voidforge.json — DO NOT EDIT.
// To refresh: start the API, save GET /swagger/v1/swagger.json to
// openapi/voidforge.json, then run `bun run generate:api`.

import { z } from 'zod';

const ResourcePoolResponse = z.object({
  currentValue: z.number(),
  rate: z.number(),
  storageCapacity: z.number(),
});
const PlanetResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  solarSystemId: z.uuid(),
  ownerId: z.uuid().nullish(),
  ironOrePool: z.number().int(),
  buildingSlotCount: z.number().int(),
  ironOre: ResourcePoolResponse,
  ironIngot: ResourcePoolResponse,
});
const RegisterPlayerRequest = z.object({ name: z.string() });
const RegisterPlayerResponse = z.object({
  playerId: z.uuid(),
  apiKey: z.string(),
  homeworldId: z.uuid(),
});
const PlayerInfoResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  registeredAt: z.iso.datetime({ offset: true }),
});
const SolarSystemResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  x: z.number(),
  y: z.number(),
  z: z.number(),
  planetIds: z.array(z.uuid()),
});

export const schemas = {
  ResourcePoolResponse,
  PlanetResponse,
  RegisterPlayerRequest,
  RegisterPlayerResponse,
  PlayerInfoResponse,
  SolarSystemResponse,
};
